### ISSUE TITLE
关于多实例学习的一些疑问

### ISSUE THREAD

**Issue by yasohasakii** [TankZhouFirst/clinical-grade-computational-pathology-using-weakly-supervised-deep-learning-on-whole-slide-images#3]
你好！我最近在做一个医学方面的多实例学习任务，刚好看到你的博客，有一些问题想问一下。
关于多实例学习数据tag的获取，目前的方法是将正例bag中所有实例不论正反实例都给上正例tag，反例bag中所有实例给上反例tag，这样的话不会有数据不平衡的问题吗？因为真实情况中正例bag中的实例有些tag是给错了的，所以这样真实的正实例的数量应该是远小于反实例的。第二，错误的tag网络能从中学到正确的特征吗，还是说我理解的学习策略有问题呢？麻烦有空帮忙解答一下，非常感谢！

**Comment by TankZhouFirst** [comment]
> 你好！我最近在做一个医学方面的多实例学习任务，刚好看到你的博客，有一些问题想问一下。
> 关于多实例学习数据tag的获取，目前的方法是将正例bag中所有实例不论正反实例都给上正例tag，反例bag中所有实例给上反例tag，这样的话不会有数据不平衡的问题吗？因为真实情况中正例bag中的实例有些tag是给错了的，所以这样真实的正实例的数量应该是远小于反实例的。第二，错误的tag网络能从中学到正确的特征吗，还是说我理解的学习策略有问题呢？麻烦有空帮忙解答一下，非常感谢！

你好，我当时也有这个疑惑，但是从验证集来看，表现还行。因为只是试验，所以未深入研究，其他部分也不是太清楚，抱歉哈
